name: Docs Build

on:
  push:
    branches-ignore:
      - main


jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-build-docs-${{ hashFiles('**/Gemfile.lock') }}
      - name: Generate docs and statuses
        run: |
          gem install bundler:2.2.9
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec rake docs:build
          bundle exec rake statuses:dump
      - name: Commit & Push Docs Data
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Actions Auto Build"
          git add -f docs static/statuses.json static/arguments.yml static/classes.yml
          git commit -m "docs: build docs" || true
          git push
      - name: Set up node js
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: Run docs
        run: |
          sudo apt-get install tmux 
          curl --fail --location --output /usr/bin/overmind.gz https://github.com/DarthSim/overmind/releases/download/v2.1.0/overmind-v2.1.0-linux-amd64.gz && \
            gunzip /usr/bin/overmind.gz && \
            chmod +x /usr/bin/overmind
          bundle exec overmind start -l rails,doctocat
          npx wait-on http://localhost:5400
      - name: Run axe checks on examples of component docs
        run: script/axe-docs
      - name: Upload @axe-core/cli check results
        uses: actions/upload-artifact@master
        with:
          path: docs-example-accessibility.json
