name: Update Statuses Board

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    name: Update statuses project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Install deps
        run: gem install graphql-client
      - name: Make updates
        run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} script/update-statuses-project.rb
